### ISSUE TITLE
Issues with controller being detected but not working

### ISSUE THREAD

**Issue by KrisZane** [Stents-/XOutput#4]
I have been testing an ipega PG-9028 bluetooth controller with your software and steam seems to detect it just fine as an xinput device in big picture mode.
However none of my games seem to be able to use it and also if I check joy.cpl in windows none of the keys light up either.

I think this software is an awesome idea and would love to offer up both of my ipega controllers for testing if you'd like.

**Comment by ericlbarrett** [comment]
I originally created this because none of my controllers were XInput compatible, since I got my own 360 controller I have sort of neglected to update it. That said, I'd like to pay more attention to this project.

In joy.cpl does your own controller cause lights to activate? Did you remember to bind the controller in XOuput?

**Comment by KrisZane** [comment]
There we go, I just added a couple of screenshots.

So below you can see DirectInput working just fine, as well as the amount of simulated controllers I have hooked up(none of which is responding and lighting up). The reason there is two is that the Ipega is a bit weird, as it has both a keyboard and controller setup at the same time, so I hooked up both to be sure.

The controller is also listed in big picture mode of steam and I also attached a picture of the keymap, which I put on both versions of the controllers, to make sure.

Also as a side note, thanks for helping out, I also gave up and purchased a steam controller instead, but now I have friends coming over, so it would be nice to be able to use these controllers I have laying around instead of buying 2-3 new ones at 50€ a piece. :P

Big picture detection:
![Steam Big Picture detection](https://cloud.githubusercontent.com/assets/12501838/10903079/46f05158-8206-11e5-8ef2-f85272482d82.png)

Key mapping I set up:
![Key mapping](https://cloud.githubusercontent.com/assets/12501838/10903076/46ed870c-8206-11e5-94a3-cb686c8c3c2b.png)

DirectInput lighting up buttons in joy.cpl:
![DirectInput working](https://cloud.githubusercontent.com/assets/12501838/10903078/46ee923c-8206-11e5-98b3-5db497115e21.png)

The controller listing:
![Hooked up controllers](https://cloud.githubusercontent.com/assets/12501838/10903077/46ee18b6-8206-11e5-9473-705d6ee237af.png)

**Comment by ericlbarrett** [comment]
Hmm...

As I said I have neglected to maintain this project. I have actually reinstalled Windows several times since my last commit. So, I downloaded the latest version (from the releases tab) and plugged in one of my DirectInput controllers and configured it. It didn't seem to work either. I then downloaded the latest source and and built a version from that and the controller worked fine. I think this is related to controller exclusivity. In release v0.1 XOutput requested exclusivity to the DirectInput devices, this caused a multitude of issues with some games. Recently after v0.1 I added a checkbox to toggle exclusivity. 

I went ahead and published a new release, v0.11. Go ahead and download and see if it improves anything for you.

**Comment by KrisZane** [comment]
That is awesome, yeah I seem to be getting it to work now, thanks a lot. :P

![1446548002 screenshot](https://cloud.githubusercontent.com/assets/12501838/10906424/a87866e8-8221-11e5-9c10-d93696a29b74.png)

If you want to start the project up again, I'd gladly help with testing, UI and the like, also thanks for saving me 100€. :P

**Comment by ericlbarrett** [comment]
No problem! If you have any other issues just submit it here.
